// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: arkanoid.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_arkanoid_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_arkanoid_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_arkanoid_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_arkanoid_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_arkanoid_2eproto;
class ElementPosition;
class ElementPositionDefaultTypeInternal;
extern ElementPositionDefaultTypeInternal _ElementPosition_default_instance_;
class GameElement;
class GameElementDefaultTypeInternal;
extern GameElementDefaultTypeInternal _GameElement_default_instance_;
class GameUpdate;
class GameUpdateDefaultTypeInternal;
extern GameUpdateDefaultTypeInternal _GameUpdate_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::ElementPosition* Arena::CreateMaybeMessage<::ElementPosition>(Arena*);
template<> ::GameElement* Arena::CreateMaybeMessage<::GameElement>(Arena*);
template<> ::GameUpdate* Arena::CreateMaybeMessage<::GameUpdate>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

enum ElementType : int {
  BALL = 0,
  PADDLE = 1,
  BRICK = 2,
  ElementType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  ElementType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool ElementType_IsValid(int value);
constexpr ElementType ElementType_MIN = BALL;
constexpr ElementType ElementType_MAX = BRICK;
constexpr int ElementType_ARRAYSIZE = ElementType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ElementType_descriptor();
template<typename T>
inline const std::string& ElementType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ElementType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ElementType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ElementType_descriptor(), enum_t_value);
}
inline bool ElementType_Parse(
    const std::string& name, ElementType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ElementType>(
    ElementType_descriptor(), name, value);
}
// ===================================================================

class ElementPosition PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ElementPosition) */ {
 public:
  inline ElementPosition() : ElementPosition(nullptr) {};
  virtual ~ElementPosition();

  ElementPosition(const ElementPosition& from);
  ElementPosition(ElementPosition&& from) noexcept
    : ElementPosition() {
    *this = ::std::move(from);
  }

  inline ElementPosition& operator=(const ElementPosition& from) {
    CopyFrom(from);
    return *this;
  }
  inline ElementPosition& operator=(ElementPosition&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ElementPosition& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ElementPosition* internal_default_instance() {
    return reinterpret_cast<const ElementPosition*>(
               &_ElementPosition_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ElementPosition& a, ElementPosition& b) {
    a.Swap(&b);
  }
  inline void Swap(ElementPosition* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ElementPosition* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ElementPosition* New() const final {
    return CreateMaybeMessage<ElementPosition>(nullptr);
  }

  ElementPosition* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ElementPosition>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ElementPosition& from);
  void MergeFrom(const ElementPosition& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ElementPosition* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ElementPosition";
  }
  protected:
  explicit ElementPosition(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_arkanoid_2eproto);
    return ::descriptor_table_arkanoid_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
  };
  // float x = 1;
  void clear_x();
  float x() const;
  void set_x(float value);
  private:
  float _internal_x() const;
  void _internal_set_x(float value);
  public:

  // float y = 2;
  void clear_y();
  float y() const;
  void set_y(float value);
  private:
  float _internal_y() const;
  void _internal_set_y(float value);
  public:

  // @@protoc_insertion_point(class_scope:ElementPosition)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  float x_;
  float y_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_arkanoid_2eproto;
};
// -------------------------------------------------------------------

class GameElement PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:GameElement) */ {
 public:
  inline GameElement() : GameElement(nullptr) {};
  virtual ~GameElement();

  GameElement(const GameElement& from);
  GameElement(GameElement&& from) noexcept
    : GameElement() {
    *this = ::std::move(from);
  }

  inline GameElement& operator=(const GameElement& from) {
    CopyFrom(from);
    return *this;
  }
  inline GameElement& operator=(GameElement&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const GameElement& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GameElement* internal_default_instance() {
    return reinterpret_cast<const GameElement*>(
               &_GameElement_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(GameElement& a, GameElement& b) {
    a.Swap(&b);
  }
  inline void Swap(GameElement* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GameElement* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline GameElement* New() const final {
    return CreateMaybeMessage<GameElement>(nullptr);
  }

  GameElement* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<GameElement>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const GameElement& from);
  void MergeFrom(const GameElement& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GameElement* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "GameElement";
  }
  protected:
  explicit GameElement(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_arkanoid_2eproto);
    return ::descriptor_table_arkanoid_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kElementPositionFieldNumber = 3,
    kIdFieldNumber = 1,
    kTypeFieldNumber = 2,
  };
  // .ElementPosition element_position = 3;
  bool has_element_position() const;
  private:
  bool _internal_has_element_position() const;
  public:
  void clear_element_position();
  const ::ElementPosition& element_position() const;
  ::ElementPosition* release_element_position();
  ::ElementPosition* mutable_element_position();
  void set_allocated_element_position(::ElementPosition* element_position);
  private:
  const ::ElementPosition& _internal_element_position() const;
  ::ElementPosition* _internal_mutable_element_position();
  public:
  void unsafe_arena_set_allocated_element_position(
      ::ElementPosition* element_position);
  ::ElementPosition* unsafe_arena_release_element_position();

  // int32 id = 1;
  void clear_id();
  ::PROTOBUF_NAMESPACE_ID::int32 id() const;
  void set_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_id() const;
  void _internal_set_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // .ElementType type = 2;
  void clear_type();
  ::ElementType type() const;
  void set_type(::ElementType value);
  private:
  ::ElementType _internal_type() const;
  void _internal_set_type(::ElementType value);
  public:

  // @@protoc_insertion_point(class_scope:GameElement)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::ElementPosition* element_position_;
  ::PROTOBUF_NAMESPACE_ID::int32 id_;
  int type_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_arkanoid_2eproto;
};
// -------------------------------------------------------------------

class GameUpdate PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:GameUpdate) */ {
 public:
  inline GameUpdate() : GameUpdate(nullptr) {};
  virtual ~GameUpdate();

  GameUpdate(const GameUpdate& from);
  GameUpdate(GameUpdate&& from) noexcept
    : GameUpdate() {
    *this = ::std::move(from);
  }

  inline GameUpdate& operator=(const GameUpdate& from) {
    CopyFrom(from);
    return *this;
  }
  inline GameUpdate& operator=(GameUpdate&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const GameUpdate& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GameUpdate* internal_default_instance() {
    return reinterpret_cast<const GameUpdate*>(
               &_GameUpdate_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(GameUpdate& a, GameUpdate& b) {
    a.Swap(&b);
  }
  inline void Swap(GameUpdate* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GameUpdate* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline GameUpdate* New() const final {
    return CreateMaybeMessage<GameUpdate>(nullptr);
  }

  GameUpdate* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<GameUpdate>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const GameUpdate& from);
  void MergeFrom(const GameUpdate& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GameUpdate* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "GameUpdate";
  }
  protected:
  explicit GameUpdate(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_arkanoid_2eproto);
    return ::descriptor_table_arkanoid_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kElementFieldNumber = 1,
  };
  // repeated .GameElement element = 1;
  int element_size() const;
  private:
  int _internal_element_size() const;
  public:
  void clear_element();
  ::GameElement* mutable_element(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::GameElement >*
      mutable_element();
  private:
  const ::GameElement& _internal_element(int index) const;
  ::GameElement* _internal_add_element();
  public:
  const ::GameElement& element(int index) const;
  ::GameElement* add_element();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::GameElement >&
      element() const;

  // @@protoc_insertion_point(class_scope:GameUpdate)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::GameElement > element_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_arkanoid_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ElementPosition

// float x = 1;
inline void ElementPosition::clear_x() {
  x_ = 0;
}
inline float ElementPosition::_internal_x() const {
  return x_;
}
inline float ElementPosition::x() const {
  // @@protoc_insertion_point(field_get:ElementPosition.x)
  return _internal_x();
}
inline void ElementPosition::_internal_set_x(float value) {
  
  x_ = value;
}
inline void ElementPosition::set_x(float value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:ElementPosition.x)
}

// float y = 2;
inline void ElementPosition::clear_y() {
  y_ = 0;
}
inline float ElementPosition::_internal_y() const {
  return y_;
}
inline float ElementPosition::y() const {
  // @@protoc_insertion_point(field_get:ElementPosition.y)
  return _internal_y();
}
inline void ElementPosition::_internal_set_y(float value) {
  
  y_ = value;
}
inline void ElementPosition::set_y(float value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:ElementPosition.y)
}

// -------------------------------------------------------------------

// GameElement

// int32 id = 1;
inline void GameElement::clear_id() {
  id_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GameElement::_internal_id() const {
  return id_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GameElement::id() const {
  // @@protoc_insertion_point(field_get:GameElement.id)
  return _internal_id();
}
inline void GameElement::_internal_set_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  id_ = value;
}
inline void GameElement::set_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:GameElement.id)
}

// .ElementType type = 2;
inline void GameElement::clear_type() {
  type_ = 0;
}
inline ::ElementType GameElement::_internal_type() const {
  return static_cast< ::ElementType >(type_);
}
inline ::ElementType GameElement::type() const {
  // @@protoc_insertion_point(field_get:GameElement.type)
  return _internal_type();
}
inline void GameElement::_internal_set_type(::ElementType value) {
  
  type_ = value;
}
inline void GameElement::set_type(::ElementType value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:GameElement.type)
}

// .ElementPosition element_position = 3;
inline bool GameElement::_internal_has_element_position() const {
  return this != internal_default_instance() && element_position_ != nullptr;
}
inline bool GameElement::has_element_position() const {
  return _internal_has_element_position();
}
inline void GameElement::clear_element_position() {
  if (GetArena() == nullptr && element_position_ != nullptr) {
    delete element_position_;
  }
  element_position_ = nullptr;
}
inline const ::ElementPosition& GameElement::_internal_element_position() const {
  const ::ElementPosition* p = element_position_;
  return p != nullptr ? *p : *reinterpret_cast<const ::ElementPosition*>(
      &::_ElementPosition_default_instance_);
}
inline const ::ElementPosition& GameElement::element_position() const {
  // @@protoc_insertion_point(field_get:GameElement.element_position)
  return _internal_element_position();
}
inline void GameElement::unsafe_arena_set_allocated_element_position(
    ::ElementPosition* element_position) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(element_position_);
  }
  element_position_ = element_position;
  if (element_position) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:GameElement.element_position)
}
inline ::ElementPosition* GameElement::release_element_position() {
  auto temp = unsafe_arena_release_element_position();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::ElementPosition* GameElement::unsafe_arena_release_element_position() {
  // @@protoc_insertion_point(field_release:GameElement.element_position)
  
  ::ElementPosition* temp = element_position_;
  element_position_ = nullptr;
  return temp;
}
inline ::ElementPosition* GameElement::_internal_mutable_element_position() {
  
  if (element_position_ == nullptr) {
    auto* p = CreateMaybeMessage<::ElementPosition>(GetArena());
    element_position_ = p;
  }
  return element_position_;
}
inline ::ElementPosition* GameElement::mutable_element_position() {
  // @@protoc_insertion_point(field_mutable:GameElement.element_position)
  return _internal_mutable_element_position();
}
inline void GameElement::set_allocated_element_position(::ElementPosition* element_position) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete element_position_;
  }
  if (element_position) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(element_position);
    if (message_arena != submessage_arena) {
      element_position = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, element_position, submessage_arena);
    }
    
  } else {
    
  }
  element_position_ = element_position;
  // @@protoc_insertion_point(field_set_allocated:GameElement.element_position)
}

// -------------------------------------------------------------------

// GameUpdate

// repeated .GameElement element = 1;
inline int GameUpdate::_internal_element_size() const {
  return element_.size();
}
inline int GameUpdate::element_size() const {
  return _internal_element_size();
}
inline void GameUpdate::clear_element() {
  element_.Clear();
}
inline ::GameElement* GameUpdate::mutable_element(int index) {
  // @@protoc_insertion_point(field_mutable:GameUpdate.element)
  return element_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::GameElement >*
GameUpdate::mutable_element() {
  // @@protoc_insertion_point(field_mutable_list:GameUpdate.element)
  return &element_;
}
inline const ::GameElement& GameUpdate::_internal_element(int index) const {
  return element_.Get(index);
}
inline const ::GameElement& GameUpdate::element(int index) const {
  // @@protoc_insertion_point(field_get:GameUpdate.element)
  return _internal_element(index);
}
inline ::GameElement* GameUpdate::_internal_add_element() {
  return element_.Add();
}
inline ::GameElement* GameUpdate::add_element() {
  // @@protoc_insertion_point(field_add:GameUpdate.element)
  return _internal_add_element();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::GameElement >&
GameUpdate::element() const {
  // @@protoc_insertion_point(field_list:GameUpdate.element)
  return element_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::ElementType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::ElementType>() {
  return ::ElementType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_arkanoid_2eproto
